In [3]:
import numpy as np
arr = [6,7,8,9]
print(type(arr))

<class 'list'>


In [4]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(4,)


In [6]:
print(a.dtype)

int32


In [7]:
print(a.ndim)

1


In [8]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
print(b.ndim)

2


In [10]:
b.shape

(2, 3)

In [11]:
b = np.random.random([2,3])

In [12]:
print(b)

[[0.3937518  0.75242369 0.21650835]
 [0.87840489 0.73942016 0.80173094]]


In [13]:
b = np.zeros([2,3])

In [14]:
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
arr = np.zeros([5,7])
print(arr)
print(type(arr))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [16]:
arr = np.ones([2,3])
print([arr])

[array([[1., 1., 1.],
       [1., 1., 1.]])]


In [17]:
arr = np.zeros(3)
print([arr])

[array([0., 0., 0.])]


In [18]:
c = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
d = np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])
print([c+d])
print([c*d])
print([5/d])
print([c**2])

[array([[13., 13., 13.],
       [10., 10., 10.]])]
[array([[36., 40., 42.],
       [ 9., 16., 21.]])]
[array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])]
[array([[81., 64., 49.],
       [ 1.,  4.,  9.]])]


In [19]:
a[0:3]

array([6, 7, 8])

In [20]:
b[0:0]

array([], shape=(0, 3), dtype=float64)

In [21]:
b[1,2]

0.0

In [22]:
arr = [6,7,8,9]
print([arr])

[[6, 7, 8, 9]]


In [23]:
a[0]

6

In [24]:
a[3]

9

In [25]:
b[0,0]

0.0

In [26]:
b[1,2]

0.0

In [27]:
c[0,1]

8.0

In [28]:
d[1,0:2]

array([9., 8.])

In [29]:
e = np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])

In [30]:
e[:3,:2] #slicing

array([[10, 11],
       [13, 14],
       [16, 17]])

In [31]:
e[:1,:3]

array([[10, 11, 12]])

In [32]:
e[:3,:2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [33]:
e[:4,:3]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [34]:
e[:4,:2] #slicing

array([[10, 11],
       [13, 14],
       [16, 17],
       [19, 20]])

In [35]:
e[[2,0,3,1],[2,1,0,2]] #integer indexing

array([18, 11, 19, 15])

In [36]:
e[e>15]

array([16, 17, 18, 19, 20, 21])

In [37]:
sum([e])

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [38]:
import pandas as pd #convention for importing pandas

In [39]:
days = pd.Series(['Monday','Tuesday','Wednesday'])
print(days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [40]:
#creating Series with a numpy array
days_list = np.array(['Monday','Tuesday','Wednesday'])
numpy_days = pd.Series(days_list)
print(numpy_days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [41]:
#using string as index
days = pd.Series(['Monday','Tuesday','Wednesday'],index = ['a','b','c'])

In [42]:
#create Series from a dictionary
days1 = pd.Series({'a':'Monday','b':'Tuesday','c':'Wednesday'})

In [43]:
print(days,days1)

a       Monday
b      Tuesday
c    Wednesday
dtype: object a       Monday
b      Tuesday
c    Wednesday
dtype: object


In [44]:
days[0]
days[1:]

b      Tuesday
c    Wednesday
dtype: object

In [45]:
days[0]

'Monday'

In [46]:
days['c']

'Wednesday'

In [47]:
print(pd.DataFrame())#prints an empty DataFrame

Empty DataFrame
Columns: []
Index: []


In [48]:
#create a DataFrame from a dictionary
df_dict = {'Country':['Ghana','Kenya','Nigeria','Togo'],'Capital':['Accra','Nairobi','Abuja','Lome'],'Population':[10000,8500,35000,12000],'Age':[60,70,80,75]}

In [49]:
df = pd.DataFrame(df_dict,index = [2,4,6,8])
print(df)

   Age  Capital  Country  Population
2   60    Accra    Ghana       10000
4   70  Nairobi    Kenya        8500
6   80    Abuja  Nigeria       35000
8   75     Lome     Togo       12000


In [50]:
df_list = df

In [51]:
df1 = pd.DataFrame(df_list,columns = ['Country','Capital','Population','Age'],index = [2,4,6,8])
print(df1)

   Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75


In [52]:
df.iloc[3]
#at, iat, iloc and loc are accessors used to retrieve dataframes.
#select the row in the at index 3

Age              75
Capital        Lome
Country        Togo
Population    12000
Name: 8, dtype: object

In [54]:
df.loc[6] #select row with index label 6

Age                80
Capital         Abuja
Country       Nigeria
Population      35000
Name: 6, dtype: object

In [55]:
df['Capital'] #select the capital column

2      Accra
4    Nairobi
6      Abuja
8       Lome
Name: Capital, dtype: object

In [56]:
df.at[6,'Country']

'Nigeria'

In [57]:
df.iat[2,0]

80

In [60]:
df['Population'].mean()

16375.0

In [61]:
df['Age'].sum()

285

In [62]:
df.mean()

Age              71.25
Population    16375.00
dtype: float64

In [63]:
df.describe 

<bound method NDFrame.describe of    Age  Capital  Country  Population
2   60    Accra    Ghana       10000
4   70  Nairobi    Kenya        8500
6   80    Abuja  Nigeria       35000
8   75     Lome     Togo       12000>

In [64]:
df.describe() #Describe function

Age    Population
count   4.000000      4.000000
mean   71.250000  16375.000000
std     8.539126  12499.166639
min    60.000000   8500.000000
25%    67.500000   9625.000000
50%    72.500000  11000.000000
75%    76.250000  17750.000000
max    80.000000  35000.000000

In [73]:
df_dict2 = {'Name':['James','Yemen','Caro',np.nan],'Profession':['Researcher','Artist','Doctor','Writer'],'Experience':[12,np.nan,10,8],'Height':[np.nan,175,180,150]}
new_df = pd.DataFrame(df_dict2)

In [72]:
new_df.isnull()

Experience  Height   Name  Profession
0       False    True  False       False
1        True   False  False       False
2       False   False  False       False
3       False   False   True       False

In [74]:
new_df.dropna()#removes rows with missing values

Experience  Height  Name Profession
2        10.0   180.0  Caro     Doctor